BIN_TARGETS = $(BINDIR)/hubDBClient $(BINDIR)/hubDBServer

hubDBClient_SRCS = hubDBClient.cpp
hubDBClient_LIBS = hubDB log4cxx
#fl
hubDBServer_SRCS = hubDBServer.cpp 
hubDBServer_LIBS = hubDB log4cxx
#fl

include ../Makefile.common
